project:
  type: website
  output-dir: docs

website:
  title: "FIP 606 | Análise de Dados em Fitopatologia"
  
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: aula1Q.qmd
        text: "Introdução"
      - href: aula2.qmd
        text: "Gráficos"
      - href: aula3.qmd
        text: "Análise Multianual de Produtividade"
      - href: aula4.qmd
        text: "Comparação de médias, teste t, testes não paramétricos e ANOVA"
      - href: aula5.qmd
        text: "ANOVA, Diagnóstico de Pressupostos, Kruskal-Wallis e GLM de Poisson"
      - href: aula6.qmd
        text: "ANOVA fatorial, blocos e correlação"
      - href: aula7.qmd
        text: "Diferença de ANOVA clássica e LMM - Comparações múltiplas"
      - href: aula08.qmd
        text: "Análise de Regressão e Modelos Mistos"

  page-footer:
    center: "Desenvolvido por Antoniel Pereira"

format:
  html:
    theme: 
      - cosmo
      - styles.scss   # 👈 vamos evoluir pra SCSS
    toc: true
    toc-location: right
    smooth-scroll: true
    code-copy: true

editor: visual